services:
  web:
    build:
      context: ..
      dockerfile: ./salon_manager/compose/local/django/Dockerfile
    image: salon_manager
    command:
      - /start
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: salon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  celery-worker:
    build:
      context: ..
      dockerfile: ./salon_manager/compose/local/django/Dockerfile
    image: celery_worker
    command: /start-celeryworker
    user: "501:501"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: ..
      dockerfile: ./salon_manager/compose/local/django/Dockerfile
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: ..
      dockerfile: ./salon_manager/compose/local/django/Dockerfile
    image: celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - db

volumes:
   postgres_data:
