# Generated by Django 5.1.6 on 2025-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_is_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("CUSTOMER", "Customer"),
                    ("EMPLOYEE", "Employee"),
                ],
                default="CUSTOMER",
                max_length=10,
            ),
        ),
    ]
