# Generated by Django 5.1.6 on 2025-04-24 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_remove_reservation_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.reservationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="reservationrequest",
            name="id_request",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
