# Generated by Django 5.1.6 on 2025-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_reservation_email_reservation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
