# Generated by Django 5.1.6 on 2025-06-20 13:26

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0007_alter_reservation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancel_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancel_token_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
