# Generated by Django 5.1.6 on 2025-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0010_auto_20250620_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="cancel_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
