# Generated by Django 5.1.6 on 2025-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_alter_reservation_cancel_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="cancel_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
