# Generated by Django 5.1.6 on 2025-06-20 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0009_alter_reservation_cancel_token"),
        ("reservations", "0012_alter_reservation_cancel_token"),
    ]

    operations = []
