# Generated by Django 5.1.6 on 2025-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0013_merge_20250620_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="cancel_token",
            field=models.UUIDField(unique=True),
        ),
    ]
