# Generated by Django 5.1.6 on 2025-07-11 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0015_remove_reservation_cancel_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationrequest",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
