# Generated by Django 5.1.6 on 2025-07-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0016_reservationrequest_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="reservations.reservationrequest",
            ),
        ),
    ]
